#pragma once

#define MASTER_LEFT
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#undef ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4
#define ENCODER_DIRECTION_FLIP

#define RGB_DI_PIN D3
#define RGB_MATRIX_LED_COUNT 74 // 2 + 12 + 58
#define RGB_HALF_LED_COUNT 36
#define RGB_MATRIX_SPLIT { RGB_HALF_LED_COUNT, RGB_HALF_LED_COUNT }

#ifdef RGB_MATRIX_ENABLE
#   define RGB_MATRIX_KEYPRESSES
#   define RGB_DISABLE_WHEN_USB_SUSPENDED
#   define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150 // Limit brightness for power
#   define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_JELLYBEAN_RAINDROPS

#   define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#endif